name: CI

on: [pull_request, push]

jobs:
  build:
    name: Build + Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '14'
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: Unit Tests
        run: npm run test:unit:coverage
      - name: E2E Tests
        run: npm run test:e2e:headless



